CalendarApp/Controllers/CalendarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BusinessLogic;
using CalendarApp.Models;
using Dao;
using DataModel.Entities;
using DataModel.Enum;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewFeatures;

namespace CalendarApp.Controllers
{
	public class CalendarController : Controller
	{
		public ICalendarManagement CalendarManagement { get; set; }

		public IPersonManagement PersonManagement { get; set; }

		public CalendarController(ICalendarManagement calendarManagement, IPersonManagement personManagement)
		{
			CalendarManagement = calendarManagement;
			PersonManagement = personManagement;
		}
		
		public IActionResult Index(int? year, int? month)
		{
			if (!year.HasValue)
				year = DateTime.Now.Year;

			if (!month.HasValue)
				month = DateTime.Now.Month;


			var model = new CalendarModel();
			model.CalendarInfo = CalendarManagement.GetMonthInfo(year.Value, month.Value);
			model.DateTime = new DateTime(year.GetValueOrDefault(), month.GetValueOrDefault(), 1);

			return View("Index", model);
		}

		public IActionResult Detail(int year, int month, int day)
		{
			var detailModel = new DetailModel();

			var detailMeetings = CalendarManagement.GetDetails(year, month, day);

			var list = new List<DetailDay>();
			var dtFrom = new DateTime(year, month, day);
			var step = 48;

			for (int i = 0; i < step; i++)
			{
				var mStep = (double)(24 * 60) / (double)step;
				var minuteStep = (double)i * mStep;
				var dateStepFrom = dtFrom.AddMinutes(minuteStep);
				var dateStepTo = dtFrom.AddMinutes(minuteStep + mStep);


				var detailItem = new DetailDay();
				detailItem.Hour = dateStepFrom.Hour;
				detailItem.Minutes = dateStepFrom.Minute;


				foreach (var meeting in detailMeetings)
				{
					var meetingFrom = meeting.Calendar.Date;
					var meetingTo = meeting.Calendar.Date.AddMinutes(meeting.Calendar.ElapsedTime);

					if (meetingFrom <= dateStepFrom && meetingTo >= dateStepTo)
					{
						var item = list.FirstOrDefault(x => x.Id == meeting.Calendar.Id);

						if (item == null)
						{
							detailItem.Id = meeting.Calendar.Id;
							detailItem.Description = meeting.Description;
							detailItem.ElapsedTime = meeting.Calendar.ElapsedTime;
							detailItem.Entries = CalendarManagement.GetEntriesForId(meeting.Calendar.Id);
						}
						detailItem.Status = meeting.Status;

					}
				}

				list.Add(detailItem);
			}

			detailModel.List = list;
			
			return PartialView("Detail", detailModel);
		}
		
		public IActionResult List()
		{
			var list = CalendarManagement.GetDetails();

			return View("List", list.ToList());
		}

		public IActionResult MainPage(string value)
		{
			if (string.IsNullOrEmpty(value))
				return Index(null, null);
			else
				return PartialView(value);
		}
		
		public IActionResult Appointment(long? id)
		{
			var model = new AppointmentModel();
			SetModelList(model);

			if (id.HasValue)
			{
				var detail = CalendarManagement.GetCalendarWithDetailById(id.Value);
				model.CalendarDetailId = detail.Id;
				model.Description = detail.Description;
				model.Date = detail.Calendar.Date;
				model.ElapsedTime = detail.Calendar.ElapsedTime;
				model.Time = detail.Calendar.Date.TimeOfDay;

				var entries = CalendarManagement.GetEntriesForId(detail.Calendar.Id);
				model.Entry = entries.ToList().Select(x => x.Id).ToArray();
				model.Status = detail.Status.GetValueOrDefault(CalendarDetailStatus.Pending);
				//set current ID & current status
			}

			
			return View(model);
		}

		[HttpPost("FromBody")]
		public IActionResult NewAppointment(AppointmentModel model)
		{
			FormResult result = new FormResult();
			try
			{
				// Message = Request.Form[nameof(Message)];
				if (!ModelState.IsValid)
				{
					SetModelList(model);
					model.Result = new FormResult() { Success = false, Message = "Comprobar los campos invalidos" };
					return View("Appointment", model);
				}
				
				var date = model.Date;
				date = date.Add(model.Time);
				
				if (model.CalendarDetailId.HasValue)
				{
					CalendarManagement.UpdateAppointment(model.CalendarDetailId.Value, model.Status, model.Description, date, model.ElapsedTime, model.Entry.ToList());
					//result = new FormResult() { Success = true, Message = "Se actualizó la reunion exitosamente." };
					return List();
				}
				else
				{
					CalendarManagement.SaveAppointment(model.Description, date, model.ElapsedTime, model.Entry.ToList());
					result = new FormResult() { Success = true, Message = "Se cargo la reunion exitosamente." };
				}

				model = new AppointmentModel();
			}
			catch (Exception e)
			{
				result = new FormResult(){Success = false, Message =  e.Message};
			}
			
			model.Result = result;
			SetModelList(model);
			return View("Appointment", model);

		}
		
		public IActionResult Delete(long detailId)
		{
			CalendarManagement.DeleteAppointment(detailId);
			return List();
		}


		private void SetModelList(AppointmentModel model)
		{
			model.Entries = PersonManagement.GetAllPersons().Select(x => new SelectListItem($"{x.LastName} - {x.Name}", x.Id.ToString())).ToList();
			model.Date = DateTime.Now;
			model.TimeTable = new List<SelectListItem>();

			for (int i = 0; i < 24; i++)
			{
				for (int a = 0; a <= 30; a += 30)
				{
					model.TimeTable.Add(new SelectListItem($"{i:D2}:{a:D2}", new TimeSpan(i, a, 0).ToString()));
				}
			}

		}
	}
}

CalendarApp/Controllers/HolidayController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Linq;
using System.Xml.Serialization;
using System.Xml.XPath;
using BusinessLogic;
using CalendarApp.Helper;
using Microsoft.AspNetCore.Mvc;
using CalendarApp.Models;
using Dao;
using DataModel.Entities;
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;

namespace CalendarApp.Controllers
{
  public class HolidayController : Controller
  {
	  public ICalendarManagement CalendarManagement { get; set; }

	  public HolidayController(ICalendarManagement calendarManagement)
	  {
		  CalendarManagement = calendarManagement;

	  }

		public IActionResult Index()
	  {
		  return View();
	  }

	  public FileResult DownloadTemplate()
	  {
		  try
		  {
			  var foo = new HolidayData();
			  var fooList = new List<Holiday>();
			  fooList.Add(new Holiday() { Name = "Descripción del feriado", Date = DateTime.MaxValue.Date });
			  fooList.Add(new Holiday() { Name = "Descripción del feriado", Date = DateTime.MaxValue.Date });
			  foo.Data = fooList.ToArray();


			  var serializer = new XMLSerializer();
			  var result = serializer.Serialize(foo);


			  MemoryStream stream = new MemoryStream();
			  StreamWriter writer = new StreamWriter(stream);
			  writer.Write(result);
			  writer.Flush();
			  stream.Position = 0;

				return File(stream, "text/xml", "Template.xml");

			}
			catch (Exception e)
		  {
			  Console.WriteLine(e);
			  throw;
		  }
		  
	  }

		[HttpPost("ImportHoliday")]
		public IActionResult Upload(IFormFile file)
		{
			var form = new FormResult();
			try
			{
				if (file == null || file.Length == 0)
					throw new Exception("Debe serleccionar un archivo no vacio.");
				
				var result = new HolidayData();

				using (var reader = file.OpenReadStream())
				using (var strReader = new StreamReader(reader))
				{
					var str = strReader.ReadToEndAsync().Result;
					var serializer = new XMLSerializer();
					result = serializer.Deserialize<HolidayData>(str);

				}

				CalendarManagement.ImportHolidays(result.Data);

				form.Message = $"Archivo importado correctamente";
				form.Success = true;

				return View("Index", form);
			}
	    catch(Exception ex)
	    {
		    form.Message = $"Error al importar el archivo. {ex.Message}";
		    form.Success = false;

		    return View("Index", form);
	    }

		}
    
  }
}

CalendarApp/Controllers/PersonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BusinessLogic;
using CalendarApp.Models;
using Dao;
using Microsoft.AspNetCore.Mvc;

namespace CalendarApp.Controllers
{
  public class PersonController : Controller
  {
    public IPersonManagement Management { get; set; }

    public PersonController(IPersonManagement management)
    {
      Management = management;
    }
		
    public IActionResult Edit(string id)
    {
      return View();
    }

		public IActionResult List()
    {
      var persons = Management.GetAllPersons();
      return View("List",persons.ToList());
    }


		public IActionResult Add(long? id)
		{
			var model = new PersonModel();
			
			if (id.HasValue)
			{
				var person = Management.GetPersonById(id.Value);
				model.Name = person.Name;
				model.LastName = person.LastName;
				model.Cellphone = person.Contacts.FirstOrDefault(x => x.Contact.Name == "Celular")?.Value;
				model.Mail = person.Contacts.FirstOrDefault(x => x.Contact.Name == "Email")?.Value;
				model.Phone = person.Contacts.FirstOrDefault(x => x.Contact.Name == "Telefono")?.Value;
				model.PersonId = person.Id;
			}
			
			return View(model);
		}


		[HttpPost]
		public IActionResult Register(PersonModel model)
		{
			FormResult result = new FormResult();
			try
			{
				if (!ModelState.IsValid)
				{
					model.Result = new FormResult() { Success = false, Message = "Comprobar los campos invalidos" };
						return View("Add", model);
				}

				if (model.PersonId.HasValue)
				{
					Management.UpdateRegister(model.PersonId.Value, model.Name, model.LastName, model.Phone, model.Cellphone, model.Mail);
					result = new FormResult() { Success = true, Message = "Se actualizó la persona exitosamente." };
					return List();
				}
				else
				{
					Management.SaveRegister(model.Name, model.LastName, model.Phone, model.Cellphone, model.Mail);
					result = new FormResult() { Success = true, Message = "Se cargo la persona exitosamente." };
				}

				model = new PersonModel();
			}
			catch (Exception e)
			{
				result = new FormResult() { Success = false, Message = e.Message };
			}

			model.Result = result;
			return View("Add", model);

		}

		public IActionResult Delete(long id)
		{
			Management.DeleteRegister(id);
			return List();
		}
		
	}
}

CalendarApp/Views/Shared/ButtonPanel.cshtml
  <a href="@Url.Action("Index", "Home")" class="col-2 btn btn-outline-dark"
     data_ajax="true"
     data_ajax_method="GET"
     data_ajax_mode="replace"
     data_ajax_update="main_form">
    <span class="fa fa-home" aria-hidden="true"></span>
    <div>Home</div>
  </a>

  <a href="@Url.Action("Add", "Person", new {id = string.Empty})" class="col-2 btn btn-outline-dark"
     data_ajax="true"
     data_ajax_method="GET"
     data_ajax_mode="replace"
     data_ajax_update="main_form">
    <span class="fa fa-address-card" aria-hidden="true"></span>
    <div>Registrar Persona</div>
</a>
  
  <a href="@Url.Action("List", "Person")" class="col-2 btn btn-outline-dark"
     data_ajax="true"
     data_ajax_method="GET"
     data_ajax_mode="replace"
     data_ajax_update="#main_form">
    <span class="fa fa-th-list" aria-hidden="true"></span>
    <div>Listar Personas</div>
</a>

<a href="@Url.Action("Appointment", "Calendar", new {id = string.Empty})" class="col-2 btn btn-outline-dark"
   data_ajax="true"
   data_ajax_method="GET"
   data_ajax_mode="replace"
   data_ajax_update="#main_form">
  <span class="fas far fa-handshake" aria-hidden="true"></span>
  <div>Agendar Reunion</div>
</a>

<a href="@Url.Action("List", "Calendar")" class="col-2 btn btn-outline-dark"
   data_ajax="true"
   data_ajax_method="GET"
   data_ajax_mode="replace"
   data_ajax_update="#main_form">
  <span class="fa fa-th-list" aria-hidden="true"></span>
  <div>Listar Reuniones</div>
</a>

  <a href="@Url.Action("Index", "Holiday")" class="col-2 btn btn-outline-dark"
     data_ajax="true"
     data_ajax_method="GET"
     data_ajax_mode="replace"
     data_ajax_update="#main_form">
	  <span class="fas fa-file-import" aria-hidden="true"></span>
	  <div>Importar Feriados</div>
  </a>

CalendarApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>@ViewData["Title"] - Calendar Application</title>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <link rel="stylesheet" href="~/css/site.css" />
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

  <script src="lib/jquery/dist/jquery.js"></script>
  <script src="lib/bootstrap/dist/js/bootstrap.js"></script>
</head>
<body>
  <header></header>
  <div class="container-fluid fill-height">
    <main role="main" class="pb-3">
      <div class="buttonPanel row">
        @await Html.PartialAsync("~/Views/Shared/ButtonPanel.cshtml")
      </div>

      @RenderBody()
    </main>
  </div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src="~/js/site.js" asp-append-version="true"></script>

  @RenderSection("Scripts", required: false)
</body>
</html>